export const PRODUCTS = {
  landing_page_copy: {
    id: 'landing_page_copy',
    name: 'Landing Page Copy',
    description: 'Copy completa para sua página de vendas',
    usd: 97,
    brl: 497,
    deadline_hours: 24,
    output_formats: ['docx', 'pdf'],
    briefing_questions: [
      'O que você vende? (produto, serviço, curso)',
      'Para quem é? (descreva seu cliente ideal)',
      'Qual o maior problema que você resolve?',
      'Qual resultado concreto o cliente obtém?',
      'Tem concorrentes? Como você é diferente?',
      'Tom preferido? (direto, inspirador, técnico)',
    ],
  },
  content_pack: {
    id: 'content_pack',
    name: 'Pacote de Conteúdo para Redes',
    description: '12 posts prontos para Instagram ou LinkedIn',
    usd: 147,
    brl: 747,
    deadline_hours: 48,
    output_formats: ['docx', 'xlsx'],
    briefing_questions: [
      'Qual rede social é prioridade? (Instagram, LinkedIn, ambos)',
      'O que você vende?',
      'Tom da marca? (profissional, descontraído, provocador)',
      'Quais temas abordar? (ou deixe livre)',
      'Referência de post que você gostou?',
      'Algum tema proibido?',
    ],
  },
  email_sequence: {
    id: 'email_sequence',
    name: 'Sequência de E-mails de Nutrição',
    description: '5 e-mails prontos para converter sua lista',
    usd: 127,
    brl: 647,
    deadline_hours: 48,
    output_formats: ['docx'],
    briefing_questions: [
      'O que você vende?',
      'Para quem é a lista? (leads frios, quentes, compradores)',
      'Qual a oferta no final da sequência?',
      'Tem desconto ou bônus para o e-mail 5?',
      'Tom da marca? (consultivo, urgente, amigável)',
      'Objeções comuns dos seus leads?',
    ],
  },
  post_instagram: {
    id: 'post_instagram',
    name: 'Post para Instagram',
    description: 'Legenda completa com hashtags e CTA',
    usd: 47,
    brl: 247,
    deadline_hours: 12,
    output_formats: ['docx'],
    briefing_questions: [
      'O que você vende?',
      'Qual o objetivo do post? (engajamento, venda, autoridade)',
      'Para quem é? (descreva seu público)',
      'Tom da marca? (direto, inspiracional, educativo)',
      'Alguma referência de post que gostou?',
      'Tem algum gancho ou tema específico?',
    ],
  },
  carrossel: {
    id: 'carrossel',
    name: 'Carrossel para Instagram',
    description: 'Carrossel de 7 slides com copy completa',
    usd: 67,
    brl: 347,
    deadline_hours: 24,
    output_formats: ['docx', 'pdf'],
    briefing_questions: [
      'O que você vende?',
      'Qual o tema do carrossel?',
      'Para quem é? (descreva seu público)',
      'Qual o objetivo? (educar, vender, engajar)',
      'Tom da marca? (profissional, descontraído, provocador)',
      'Alguma referência de carrossel que gostou?',
    ],
  },
  reels_script: {
    id: 'reels_script',
    name: 'Roteiro de Reels',
    description: 'Roteiro completo com indicações visuais e cortes',
    usd: 57,
    brl: 297,
    deadline_hours: 12,
    output_formats: ['docx'],
    briefing_questions: [
      'O que você vende?',
      'Qual o tema do vídeo?',
      'Duração preferida? (30s, 60s, 90s)',
      'Quem aparece no vídeo? (você, locução, só texto)',
      'Tom? (rápido e direto, storytelling, educativo)',
      'Alguma referência de Reels que gostou?',
    ],
  },
  ad_copy: {
    id: 'ad_copy',
    name: 'Copy para Meta Ads',
    description: 'Headlines + texto para anúncios Meta (Facebook/Instagram)',
    usd: 77,
    brl: 397,
    deadline_hours: 12,
    output_formats: ['docx'],
    briefing_questions: [
      'O que você vende?',
      'Para quem é o anúncio? (público-alvo)',
      'Qual o objetivo? (venda, leads, tráfego)',
      'Tem landing page pronta? (cole o link se sim)',
      'Qual o diferencial do produto/serviço?',
      'Orçamento diário aproximado? (nos ajuda a calibrar o tom)',
    ],
  },
  app: {
    id: 'app',
    name: 'App Web',
    description: 'App interativo (calculadora, quiz, formulário, gerador)',
    usd: 97,
    brl: 497,
    deadline_hours: 24,
    output_formats: ['html'],
    briefing_questions: [
      'O que o app deve fazer?',
      'Tipo de app? (calculadora, quiz, formulário, gerador, captura)',
      'Para quem é? (descreva seu público)',
      'Alguma funcionalidade específica obrigatória?',
      'Cores ou estilo visual preferido?',
      'O que deve acontecer quando o usuário completar a ação?',
    ],
  },
} as const

export type ProductId = keyof typeof PRODUCTS
